### ISSUE TITLE
Logo invoice can not work on specific server

### ISSUE THREAD

**Issue by ClicShopping** [ClicShopping/ClicShopping_V3#18]
**Describe the bug**
on specific server or configuration server, a bug can appears when the pdfis generated. the logo is not found.

**To Reproduce**
1. Go to order
2. Click on generate order pdf
3. See error

**Expected behavior**
log error

`PHP Warning:  imagecreatefromgif(/sources/images/logos/invoice/invoice_logo.gif): Failed to open stream: No such file or directory in /home/........./includes/ClicShopping/External/vendor/setasign/fpdf/fpdf.php on line 1412
[13-Jun-2022 05:48:42 UTC] PHP Fatal error:  Uncaught Exception: FPDF error: Missing or incorrect image file: /sources/images/logos/invoice/invoice_logo.gif in /home/........./includes/ClicShopping/External/vendor/setasign/fpdf/fpdf.php:269
Stack trace:
#0 /home/........./includes/ClicShopping/External/vendor/setasign/fpdf/fpdf.php(1414): FPDF->Error()
#1 /home/........./includes/ClicShopping/External/vendor/setasign/fpdf/fpdf.php(883): FPDF->_parsegif()
#2 /home/........./includes/ClicShopping/Apps/Orders/Orders/Sites/ClicShoppingAdmin/Pages/Home/templates/invoice.php(111): FPDF->Image()
#3 /home/........./ClicShoppingAdmin83/index.php(41): include('/home/...')`

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by ClicShopping** [comment]
fixit ! I hope !
